apiVersion: v2
name: my-app
version: 1.0.0
dependencies:
  - name: redis
    version: 17.1.3
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: postgresql
    version: 13.2.15
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled