apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 'dev'
resources:
  - ../base
configMapGenerator:
  - name: dev-values-configmap
    files:
      - values.yml  # Adjust path as needed
    options:
      disableNameSuffixHash: true  # Prevent hash suffix