apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 'dev'
resources:
  - ../base
configMapGenerator:
  - name: dev-values-configmap
    files:
      - values.yml 

# Patch the HelmRelease to use the ConfigMap
patches:
  - target:
      kind: HelmRelease
      name: my-app
    patch: |-
      - op: add
        path: /spec/valuesFrom
        value:
          - kind: ConfigMap
            name: dev-values-configmap
            valuesKey: values.yml