apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-app-dev
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: .
      version: 1.0.1
      sourceRef:
        kind: GitRepository
        name: helm-package-manager
        namespace: dev
  valuesFrom:
    - kind: ConfigMap
      name: dev-values-configmap
      valuesKey: values.yml  # Only one line here