apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-app-dev
  namespace: dev
spec:
  interval: 1m
  chart:
    spec:
      chart: my-app
      version: 1.0.3
      sourceRef:
        kind: GitRepository
        name: helm-package-manager
        namespace: dev
  upgrade: 
    force: true 
  valuesFrom:
    - kind: ConfigMap
      name: dev-values-configmap
      valuesKey: values.yml  # Only one line here
      optional: true 